### ISSUE TITLE
Azure API Management check

### ISSUE THREAD

**Issue by Nicwalle** [Azure/azure-health-check#5]
```[tasklist]
### Tasks
- [x] Available Zones
- [x] API Descriptors
- [x] Certificate Expiry
- [x] Defender Cloud (access issue)
- [x] Encrypt Values
- [x] Min API version
- [x] Multi Region
- [x] Policy Base (access issue)
- [x] Protocols
- [x] Ciphers
- [x] Product Approval
- [x] Product descriptors
- [x] Product Subscriptions
- [x] Sample Product
- [x] Managed Identity
- [x] Multi-Region Gateway (wip)
```
